### ISSUE TITLE
Allow upload types to render with an image instead of a magick render

### ISSUE THREAD

**Issue by josefnpat** [karai17/lapis-chan#40]
I don't know what the code looks like now, but perhaps something like:

``` lua
upload_types = {
  png => {mimetype=>'image/png', render=>'magick'},
  love => {mimetype=>'archive/zip', image=>'images/love.png'},
  lua => {mimetype=>'raw/text', image=>'images/lua.png', render=>'code:lua'},
}
```

reference:

![image](https://cloud.githubusercontent.com/assets/646162/13026148/7feb0dae-d1e3-11e5-8252-1589f2e9678f.png)

**Comment by karai17** [comment]
A set of images for non-image file types would be handy. I am not currently looking at the file's mime type but I should start doing that for this specific case.

**Comment by karai17** [comment]
I updated the whitelist to have categories. I've added an audio thumbnail to the `/static` so that any filetypes listed under the audio category will pull that thumbnail.

I was going to add an archive category but @shakesoda convinced me otherwise. There are other places you can upload .loves or .zips such as mixtape.moe. Lapis-chan will remain media-focused for the foreseeable future.

Now that Lapis-chan depends on FFmpeg, it's not unreasonable to add video support, but I feel like it's kind of out of scope. For now, it's just images + webm, and audio.

If you have other category or filetype idea,s please open a new issue.
