### ISSUE TITLE
Read bytes from /dev/urandom instead of weird PRNG

### ISSUE THREAD

**Issue by kyle-emmerich** [karai17/lapis-chan#44]
holo informs me this isn't supposed to be crypto-secure but it's worth checking out anyway since it's way easier

**Comment by karai17** [comment]
What weird prng are you referring to?

**Comment by kyle-emmerich** [comment]
generate.random()

return sf("%s%s", time, tn("0x" .. ss(ts(t), -6))) seems pretty nutty

**Comment by karai17** [comment]
Uploaded images use a time stamp for the file name, and are appended with a random 3 digits to help alleviate issues where two people upload images at the same time. The issue here was that math.random was using the same number. My fever dream solution was to find something that was guaranteed to be different (waddup memory addresses) and then use those as numbers. It works, but I agree it is... nutty.

I've never really done much that was Linux-specific when it comes to programming, so I am unsure how to query /dev/urandom. Can you give me an example?

**Comment by kyle-emmerich** [comment]
```
function generateRandomNumber()
     local r = io.open("/dev/urandom", "rb") --read binary
     local bytes = r:read(4)
     local num = ffi.new("unsigned int[1]")
     ffi.copy(num, bytes, 4)
     r:close()
     return num[0]
end
```

That'd probably do it

**Comment by karai17** [comment]
Every example I see for urandom suggests reading 4 bytes. Is that for any particular reason, or is it just snagging a 32-bit integer?

**Comment by kyle-emmerich** [comment]
Yeah, that's pretty much it. You can read any number of bytes you want.

Also, it seems like you'll find a lot of people saying not to use /dev/urandom, but ignore it. /dev/random will block if it "runs out" of entropy but /dev/urandom will continue giving you pseudorandom numbers that are still cryptographically secure. Not entirely relevant, but good to know.

**Comment by karai17** [comment]
Yeah, cryptography isn't exactly a priority in this case, I just need to prevent filename collision.
